services:
  n8n:
    image: n8nio/n8n:2.20.7
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      # Database
      - DB_TYPE=${N8N_DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_HOSTNAME}
      - DB_POSTGRESDB_PORT=${DB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}

      # n8n config
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}

      - GENERIC_TIMEZONE=${N8N_TIMEZONE}

      # Security
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    depends_on:
      db:
        condition: service_healthy
  app:
    hostname: app
    container_name: app
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
  migrate:
    command: bun run db:migrate
    hostname: app-migrate
    container_name: app-migrate
    restart: 'no'
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres:18
    hostname: db
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
  caddy:
    image: caddy:latest
    hostname: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
