services:
  n8n:
    expose:
      - '5678'
    volumes:
      - /data/n8n_data:/home/node/.n8n
  app:
    image: ${APP_IMAGE}
    expose:
      - '3000'
    env_file:
      - .env
  migrate:
    image: ${MIGRATE_IMAGE}
    env_file:
      - .env
  db:
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro
  caddy:
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /data/caddy/data:/data
      - /data/caddy/config:/config
    depends_on:
      - app
